/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.util.HashSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Car;
import model.CarHistory;

/**
 *
 * @author spz
 */
public class SearchJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SearchJPanel
     */
    CarHistory history;

    public SearchJPanel(CarHistory history) {
        initComponents();

        this.history = history;
        clearTbl();

        populateTable();
        populateCombo();
        //populateSelectedCar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblCar = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblSelectedCar = new javax.swing.JTable();
        cmbBrand = new javax.swing.JComboBox<>();
        lblBrand = new javax.swing.JLabel();
        lblFirstCar = new javax.swing.JButton();
        btnAvailableNum = new javax.swing.JButton();
        txtAvailableNum = new javax.swing.JTextField();
        txtYear = new javax.swing.JTextField();
        txtSeat1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtSeat2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnShowSeats = new javax.swing.JButton();
        btnShowYear = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtSerial = new javax.swing.JTextField();
        btnShowSerial = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtModel = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtCity = new javax.swing.JTextField();
        btnShowCity = new javax.swing.JButton();
        btnShowModel = new javax.swing.JButton();
        btnExpired = new javax.swing.JButton();

        tblCar.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        tblCar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Distance", "Vacant", "Brand", "Year", "Seats", "Serial", "Model", "Fleet updated year", "City", "Maintain"
            }
        ));
        tblCar.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jScrollPane1.setViewportView(tblCar);

        tblSelectedCar.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        tblSelectedCar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Distance", "Vacant", "Brand", "Year", "Seats", "Serial", "Model", "Fleet", "City", "Maintain"
            }
        ));
        tblSelectedCar.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jScrollPane2.setViewportView(tblSelectedCar);

        cmbBrand.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbBrand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbBrandActionPerformed(evt);
            }
        });

        lblBrand.setText("Select Brand");

        lblFirstCar.setText("First Available Car");
        lblFirstCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblFirstCarActionPerformed(evt);
            }
        });

        btnAvailableNum.setText("Number of Available Cars");
        btnAvailableNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAvailableNumActionPerformed(evt);
            }
        });

        txtAvailableNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAvailableNumActionPerformed(evt);
            }
        });

        txtYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtYearActionPerformed(evt);
            }
        });

        txtSeat1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSeat1ActionPerformed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("and");

        jLabel2.setText("Cars with seats between");

        txtSeat2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSeat2ActionPerformed(evt);
            }
        });

        jLabel3.setText("Show the cars made in (year)");

        btnShowSeats.setText("Search");
        btnShowSeats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowSeatsActionPerformed(evt);
            }
        });

        btnShowYear.setText("Search");
        btnShowYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowYearActionPerformed(evt);
            }
        });

        jLabel4.setText("Car with serial number");

        btnShowSerial.setText("Search");
        btnShowSerial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowSerialActionPerformed(evt);
            }
        });

        jLabel5.setText("Cars with specific model");

        jLabel6.setText("Cars available in which city");

        btnShowCity.setText("Search");
        btnShowCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowCityActionPerformed(evt);
            }
        });

        btnShowModel.setText("Search");
        btnShowModel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowModelActionPerformed(evt);
            }
        });

        btnExpired.setText("Cars expired maintenance certificate");
        btnExpired.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExpiredActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 927, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblBrand, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cmbBrand, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(lblFirstCar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnAvailableNum, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnExpired, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtAvailableNum, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(86, 86, 86)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtSeat1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(txtSeat2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtYear)
                            .addComponent(txtSerial)
                            .addComponent(txtCity)
                            .addComponent(txtModel))
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnShowYear)
                            .addComponent(btnShowSeats)
                            .addComponent(btnShowSerial)
                            .addComponent(btnShowCity)
                            .addComponent(btnShowModel))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 927, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtSeat1, txtSeat2});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblBrand, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbBrand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblFirstCar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAvailableNum)
                            .addComponent(txtAvailableNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnExpired))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnShowYear)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSeat1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSeat2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnShowSeats)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSerial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnShowSerial)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnShowCity)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnShowModel)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5)))))
                .addGap(34, 34, 34)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(97, 97, 97))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtSeat1, txtSeat2});

    }// </editor-fold>//GEN-END:initComponents


    private void cmbBrandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbBrandActionPerformed
        // TODO add your handling code here:
        populateSelectedCar();
    }//GEN-LAST:event_cmbBrandActionPerformed

    private void lblFirstCarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblFirstCarActionPerformed
        // TODO add your handling code here:
        Car tmp = new Car();
        tmp.setDistance(100);
        clearTbl();

        for (Car c : history.getHistory()) {
            if (c.getDistance() < tmp.getDistance()) {
                tmp = c;
            }
        }
        populateNormal(tmp);

    }//GEN-LAST:event_lblFirstCarActionPerformed

    private void btnAvailableNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAvailableNumActionPerformed
        // TODO add your handling code here:
        int count = 0;
        clearTbl();

        for (Car c : history.getHistory()) {
            if (c.getVacant() && c.getDistance() < 20) {
                populateNormal(c);
                count++;
            }
        }
        txtAvailableNum.setText(String.valueOf(count));
    }//GEN-LAST:event_btnAvailableNumActionPerformed

    private void btnExpiredActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExpiredActionPerformed
        // TODO add your handling code here:
        clearTbl();
        for (Car c : history.getHistory()) {
            if (!c.getMaintain()) {
                populateNormal(c);
            }
        }
    }//GEN-LAST:event_btnExpiredActionPerformed

    private void txtAvailableNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAvailableNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAvailableNumActionPerformed

    private void btnShowYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowYearActionPerformed
        // TODO add your handling code here:
        clearTbl();
        int count = 0;
        

        
                if("".equals(txtYear.getText())){
        JOptionPane.showMessageDialog(this, "Please type in anything for searching!");
        } else {
                    int year = Integer.parseInt(txtYear.getText());
        for(Car c : history.getHistory()){
            if (year == c.getYear())
            {
            populateNormal(c);
            count++;
            }       
        
        }
        if(count == 0){
        JOptionPane.showMessageDialog(this, "No result found!");
        }
        }
        
    }//GEN-LAST:event_btnShowYearActionPerformed

    private void txtYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtYearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtYearActionPerformed

    private void txtSeat1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSeat1ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtSeat1ActionPerformed

    private void txtSeat2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSeat2ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtSeat2ActionPerformed

    private void btnShowSeatsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowSeatsActionPerformed
        // TODO add your handling code here:
        clearTbl();
        int count = 0;
        if (!"".equals(txtSeat1.getText())) {
            int seat1 = Integer.parseInt(txtSeat1.getText());
            if (!"".equals(txtSeat2.getText())) {
                int seat2 = Integer.parseInt(txtSeat2.getText());
                for (Car c : history.getHistory()) {
                    if (c.getSeats() > seat1 && c.getSeats() < seat2) {
                        populateNormal(c);
                        count++;
                    }
                }
            } else {
                for (Car c : history.getHistory()) {
                    if (c.getSeats() > seat1) {
                        populateNormal(c);
                        count++;
                    }
                }
            }
        } else {
            if (!"".equals(txtSeat2.getText())) {
                int seat2 = Integer.parseInt(txtSeat2.getText());
                for (Car c : history.getHistory()) {
                    if (c.getSeats() < seat2) {
                        populateNormal(c);
                        count++;
                    }
                }
            } else {
                JOptionPane.showMessageDialog(this, "Please type in at least one limit!");
            }

        }
        //int seat1 = Integer.parseInt(txtSeat1.getText());
        //int seat2 = Integer.parseInt(txtSeat2.getText());
        //if(seat1)
    }//GEN-LAST:event_btnShowSeatsActionPerformed

    private void btnShowSerialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowSerialActionPerformed
        // TODO add your handling code here:
        clearTbl();
        int count = 0;
        
        if("".equals(txtSerial.getText())){
        JOptionPane.showMessageDialog(this, "Please type in anything for searching!");
        } else {
        for(Car c : history.getHistory()){
            if(c.getSerial().contains(txtSerial.getText()))
            {
            populateNormal(c);
            count++;
            }       
        
        }
        if(count == 0){
        JOptionPane.showMessageDialog(this, "No result found!");
        }
        }
        
    }//GEN-LAST:event_btnShowSerialActionPerformed

    private void btnShowCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowCityActionPerformed
        // TODO add your handling code here:
                clearTbl();
        int count = 0;
        if("".equals(txtCity.getText())){
        JOptionPane.showMessageDialog(this, "Please type in anything for searching!");
        } else {
        for(Car c : history.getHistory()){
            if(c.getCity().contains(txtCity.getText()))
            {
            populateNormal(c);
            count++;
            }       
        
        }
        if(count == 0){
        JOptionPane.showMessageDialog(this, "No result found!");
        }
        }
    }//GEN-LAST:event_btnShowCityActionPerformed

    private void btnShowModelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowModelActionPerformed
        // TODO add your handling code here:
                        clearTbl();
        int count = 0;
        if("".equals(txtModel.getText())){
        JOptionPane.showMessageDialog(this, "Please type in anything for searching!");
        } else {
        for(Car c : history.getHistory()){
            if(c.getModel().contains(txtModel.getText()))
            {
            populateNormal(c);
            count++;
            }       
        
        }
        if(count == 0){
        JOptionPane.showMessageDialog(this, "No result found!");
        }
        }
        
    }//GEN-LAST:event_btnShowModelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAvailableNum;
    private javax.swing.JButton btnExpired;
    private javax.swing.JButton btnShowCity;
    private javax.swing.JButton btnShowModel;
    private javax.swing.JButton btnShowSeats;
    private javax.swing.JButton btnShowSerial;
    private javax.swing.JButton btnShowYear;
    private javax.swing.JComboBox<String> cmbBrand;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblBrand;
    private javax.swing.JButton lblFirstCar;
    private javax.swing.JTable tblCar;
    private javax.swing.JTable tblSelectedCar;
    private javax.swing.JTextField txtAvailableNum;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtModel;
    private javax.swing.JTextField txtSeat1;
    private javax.swing.JTextField txtSeat2;
    private javax.swing.JTextField txtSerial;
    private javax.swing.JTextField txtYear;
    // End of variables declaration//GEN-END:variables

    private void populateTable() {

        DefaultTableModel model = (DefaultTableModel) tblCar.getModel();
        model.setRowCount(0);

        for (Car car : history.getHistory()) {
            Object[] row = new Object[10];
            //row[0] = car.getDistance();
            row[0] = car;
            row[1] = car.getVacant();
            row[2] = car.getBrand();
            row[3] = car.getYear();
            row[4] = car.getSeats();
            row[5] = car.getSerial();
            row[6] = car.getModel();
            row[7] = car.getFleet();
            row[8] = car.getCity();
            row[9] = car.getMaintain();

            model.addRow(row);
        }
    }

    private void populateCombo() {

        cmbBrand.removeAllItems();
        cmbBrand.addItem("<none>");
        HashSet<String> brand = new HashSet<String>();

        for (Car c : history.getHistory()) {
            if (!brand.contains(c.getBrand())) {
                brand.add(c.getBrand());
                cmbBrand.addItem(c.getBrand());
            }
        }
    }

    private void populateSelectedCar() {

        String selectedBrand = (String) cmbBrand.getSelectedItem();
        //Car selectedCar = (Car) cmbBrand.getSelectedItem();
        if (selectedBrand == null) {
            return;
        }

        DefaultTableModel model = (DefaultTableModel) tblSelectedCar.getModel();
        model.setRowCount(0);

        for (Car c : history.getHistory()) {
            if (selectedBrand.equalsIgnoreCase(c.getBrand())) {
                Object[] row = new Object[10];
                //row[0] = car.getDistance();
                row[0] = c;
                row[1] = c.getVacant();
                row[2] = c.getBrand();
                row[3] = c.getYear();
                row[4] = c.getSeats();
                row[5] = c.getSerial();
                row[6] = c.getModel();
                row[7] = c.getFleet();
                row[8] = c.getCity();
                row[9] = c.getMaintain();
                model.addRow(row);
            }
        }

    }

    private void populateNormal(Car car) {
        DefaultTableModel model = (DefaultTableModel) tblSelectedCar.getModel();
        //model.setRowCount(0);

        Object[] row = new Object[10];
        //row[0] = car.getDistance();
        row[0] = car;
        row[1] = car.getVacant();
        row[2] = car.getBrand();
        row[3] = car.getYear();
        row[4] = car.getSeats();
        row[5] = car.getSerial();
        row[6] = car.getModel();
        row[7] = car.getFleet();
        row[8] = car.getCity();
        row[9] = car.getMaintain();
        model.addRow(row);
    }

    private void clearTbl() {
        DefaultTableModel model = (DefaultTableModel) tblSelectedCar.getModel();
        model.setRowCount(0);
    }

}

/*

public class LoginSupplierJPanel extends javax.swing.JPanel {
    
    private JPanel userProcessContainer;
    private SupplierDirectory supplierDirectory;
    public LoginSupplierJPanel(JPanel upc, SupplierDirectory sd) {
        initComponents();
        userProcessContainer = upc;
        supplierDirectory = sd;
        
        cmbSupplier.removeAllItems();;
        for (Supplier supplier : supplierDirectory.getSupplierlist()) {
            cmbSupplier.addItem(supplier);
        }
    }
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblSupplierChooser = new javax.swing.JLabel();
        cmbSupplier = new javax.swing.JComboBox();
        btnFind = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(650, 600));

        lblTitle.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        lblTitle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/logoPleaseBuySmall.png"))); // NOI18N
        lblTitle.setText("Supplier Portal");
        lblTitle.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        lblTitle.setIconTextGap(50);

        lblSupplierChooser.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblSupplierChooser.setText("Choose your supplier account:");

        cmbSupplier.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbSupplierActionPerformed(evt);
            }
        });

        btnFind.setText("Login >>");
        btnFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(230, 230, 230)
                        .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(lblSupplierChooser)
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnFind)
                            .addComponent(cmbSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(42, 42, 42))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(lblTitle)
                .addGap(92, 92, 92)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSupplierChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnFind, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>                        

    private void btnFindActionPerformed(java.awt.event.ActionEvent evt) {                                        

        Supplier supplier = (Supplier) cmbSupplier.getSelectedItem();
        SupplierWorkAreaJPanel swajp = new SupplierWorkAreaJPanel(userProcessContainer, supplier);
        userProcessContainer.add("SupplierWorkAreaJPanel", swajp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }                                       

    private void cmbSupplierActionPerformed(java.awt.event.ActionEvent evt) {                                            

    }                                           
    
    
    // Variables declaration - do not modify                     
    private javax.swing.JButton btnFind;
    private javax.swing.JComboBox cmbSupplier;
    private javax.swing.JLabel lblSupplierChooser;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration                   
    
}
*/
